### PR TITLE
Fix z-order for splitbar

### PR DESCRIPTION
**Pull request by Tooa**
This pull requests addresses the problem mentioned in #140. 

Best Uli

### CODE REVIEW

**Comment by SomeKittens** [comment]
I'll have to check to see why it was done that way, though this seems more reasonable than setting them to `1010`.

Can you amend your commit message to conform to the Angular [commit guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit)?

**Comment by Tooa** [comment]
Done. The guidelines also state that the request should be from a new branch. However, this pull request is from master. Is this a problem?

**Comment by SomeKittens** [comment]
From a separate repo master is fine.

**Comment by SomeKittens** [comment]
Landed in e331104fcbb6be9cd4a71c5733b07159168481d0

Thanks!

**Pull request closed without merging**
