### PR TITLE
Fix minification

### PR DESCRIPTION
**Pull request by grantHarris**
Our minification ran into issues with uiLayoutLoaded directive as it was missing the dependency injection strings. I have added the missing strings.

### CODE REVIEW

**Comment by SomeKittens** [comment]
Thanks!  Can you squash these down to a single commit that follows the Angular commit guidelines?

**Comment by grantHarris** [comment]
No prob, all done!

**Comment by SomeKittens** [comment]
Fantastic!

**Comment by SomeKittens** [comment]
Landed in https://github.com/angular-ui/ui-layout/commit/5e684177afc53dc2baee0378f65dbf2d33825046

**Pull request closed without merging**
